export const wujiangData = [
  {
    season: "S1",
    name: "于禁",
    faction: "魏",
    roles: [],
    arms: ["盾兵"],
    base_stats: { 武力: 104, 智力: 81, 统率: 101, 先攻: 67 },
    innate_skill: {
      season: "S1",
      name: "持军毅重",
      description:
        "自身统率提升30点,每回合首次受到伤害后使敌军随机两人受到伤害提升8%(受统率影响),并有60%概率使攻击者缴械,持续2回合",
      trigger: "被动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "关平",
    faction: "蜀",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 81, 智力: 73, 统率: 89, 先攻: 25 },
    innate_skill: {
      season: "S1",
      name: "龙吟四海",
      description:
        "自身造成兵刃伤害后有37.75%概率触发龙吟:对日标施加畏惧，,持续2回合,若目标已处于畏惧状态，则改对其造成100%兵刃伤害。每回合可触发4次龙吟",
      trigger: "被动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "关羽",
    faction: "蜀",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 120.0, 智力: 86.0, 统率: 104.0, 先攻: 79.0 },
    innate_skill: {
      season: "S1",
      name: "威震华夏",
      description:
        "提升自身8%主动战法发动率,每有1个带有畏惧状态的敌军额外提升3%,持续2回合。然后对敌军全体造成160%兵刃伤害,若目标持有控制状态，则使目标产生逃兵(受武力影响)",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "典韦",
    faction: "魏",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 104, 智力: 81, 统率: 101, 先攻: 67 },
    innate_skill: {
      season: "S1",
      name: "古之来恶",
      description:
        "自身反击率提升60%,自身受到伤害后提升自身20%反击伤害和20点统率，持续2回合，可叠加5次",
      trigger: "被动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "刘备",
    faction: "蜀",
    roles: [],
    arms: ["盾兵"],
    base_stats: { 武力: 88, 智力: 87, 统率: 86, 先攻: 40 },
    innate_skill: {
      season: "S1",
      name: "携民渡江",
      description:
        "战斗开始时,提升我军全体18点统率(受智力影响),每回合结束时，恢复我军全体兵力(治疗率100%),然后驱散我军兵力最低单体1种负面状态并对其额外进行1次恢复(治疗率90%)",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "华佗",
    faction: "群",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 41, 智力: 113, 统率: 87, 先攻: 62 },
    innate_skill: {
      season: "S1",
      name: "麻沸散",
      description:
        "回合结束时,使我军兵力最低单体受到伤害降低14%(受智力影响)对其施加清醒,持续1回合。并恢复其兵力(治疗率200%)",
      trigger: "被动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "华雄",
    faction: "群",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 105, 智力: 49, 统率: 99, 先攻: 47 },
    innate_skill: {
      season: "S1",
      name: "耀武扬威",
      description:
        "技穷自身2回合,对敌军随机单体造成250%兵刃伤害和1次普通攻击(无视缴械状态)",
      trigger: "主动",
      probability: 10,
    },
  },
  {
    season: "S1",
    name: "吕布",
    faction: "群",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 125, 智力: 38, 统率: 93, 先攻: 76 },
    innate_skill: {
      season: "S1",
      name: "骁勇无前",
      description:
        "与敌军全体相互进行1次普攻(互相普攻过程中自身免疫缴械状态)。若自身武力值高于目标，则额外造成100%兵刃伤害",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "吕蒙",
    faction: "吴",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 93.0, 智力: 106.0, 统率: 103.0, 先攻: 77.0 },
    innate_skill: {
      season: "S1",
      name: "白衣渡江",
      description:
        "对敌军随机两人造成160%谋略伤害,并施加断粮,持续2回合,若目标已处于断粮状态则额外对目标造成80%谋略伤害",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "周仓",
    faction: "蜀",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 81, 智力: 73, 统率: 89, 先攻: 25 },
    innate_skill: {
      season: "S1",
      name: "忠烈勇武",
      description:
        "每个回合行动时恢复自身兵力(治疗率200%,额外受统率影响)，有40%概率对敌军随机两人施加嘲讽和畏惧状态，持续2回合",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "周瑜",
    faction: "吴",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 89, 智力: 87, 统率: 107, 先攻: 34 },
    innate_skill: {
      season: "S1",
      name: "临机制胜",
      description:
        "战斗中,敌我全体被施加异常状态时,有70%概率触发制胜:立刻对敌军随机两人造成60%谋略伤害。每回合制胜最多触发4次。累积触发4次制胜后，恢复我军全体兵力(治疗率40%)",
      trigger: "被动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "夏侯渊",
    faction: "魏",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 104, 智力: 81, 统率: 101, 先攻: 67 },
    innate_skill: {
      season: "S1",
      name: "神速奔袭",
      description:
        "每个回合行动时自身武力值提升,提升值为先攻值的40%,持续1回。若自身在先攻判定时处于首位,则获得1回合神速效果:造成伤害和会心几率提升12.25%",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "大乔",
    faction: "吴",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 24.0, 智力: 95.0, 统率: 106.0, 先攻: 35.0 },
    innate_skill: {
      season: "S1",
      name: "国色",
      description:
        "每个回合开始时,敌军随机两人受到伤害提升20%,恢复我军随机两人兵力(治疗率180%)",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "太史慈",
    faction: "吴",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 110.0, 智力: 94.0, 统率: 108.0, 先攻: 80.0 },
    innate_skill: {
      season: "S1",
      name: "弦无虚发",
      description:
        "每个回合开始时,有90%概率获得1层蓄力:成功普通攻击后可消耗所有蓄力层数进行额外的普通攻击(无视缴械状态,普通攻击次数等于蓄力层数)。自身普通攻击前,若处于缴械或无法普通攻击状态,则有90%概率获得1层蓄力",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "孙坚",
    faction: "吴",
    roles: [],
    arms: ["盾兵"],
    base_stats: { 武力: 89, 智力: 87, 统率: 107, 先攻: 34 },
    innate_skill: {
      season: "S1",
      name: "武烈破虏",
      description:
        "降低敌军随机单体40点统率(受武力或统率最高值影响),持续2回合并造成250%兵刃伤害,若目标统率低于自身则额外施加震慑,持续1回合，高于自身则使降低统率效果提升50%",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "孙尚香",
    faction: "吴",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 89, 智力: 87, 统率: 107, 先攻: 34 },
    innate_skill: {
      season: "S1",
      name: "腰弓姬",
      description:
        "普通攻击后,对敌军随机单体造成320%兵刃伤害,每有1名异性敌人，该次伤害系数提升30%，75%概率优先选择后排目标",
      trigger: "追击",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "孙权",
    faction: "吴",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 90, 智力: 96, 统率: 101, 先攻: 74 },
    innate_skill: {
      season: "S1",
      name: "虎踞江东",
      description:
        "自身每学习一个主动战法,我军全体提升3.7%主动战法发动率 自身每学习一个非主动战法，我军全体提升28%连击率 (对自身的提升效果受最高属性影响)",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "孙策",
    faction: "吴",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 112.0, 智力: 77.0, 统率: 110.0, 先攻: 74.0 },
    innate_skill: {
      season: "S1",
      name: "制霸江东",
      description:
        "对敌军随机两人造成200%兵刃伤害(自身为后排时，兵刃系数提升50%),并恢复自身兵力(治疗率100%,额外受武力影响,自身为前排时，治疗系数提升30%)",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "小乔",
    faction: "吴",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 22.0, 智力: 94.0, 统率: 88.0, 先攻: 73.0 },
    innate_skill: {
      season: "S1",
      name: "天香",
      description:
        "对敌军随机两人施加虚弱,持续1回合。恢复我军随机两人兵力(治疗率为250%)",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "庞德",
    faction: "群",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 107, 智力: 71, 统率: 101, 先攻: 59 },
    innate_skill: {
      season: "S1",
      name: "陷阵蹈难",
      description:
        "战斗第3,5回合,降低敌军全体30点统率和智力(受武力影响),持续2回合，随后造成340%兵刃伤害",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "张梁",
    faction: "群",
    roles: [],
    arms: ["盾兵"],
    base_stats: { 武力: 35, 智力: 101, 统率: 92, 先攻: 59 },
    innate_skill: {
      season: "S1",
      name: "妖武",
      description:
        "自身倒戈和规避率提升12.25%,持续2回合,然后对敌军随机两人造成220%兵刃伤害,并施加妖术，持续2回合",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "张角",
    faction: "群",
    roles: [],
    arms: ["盾兵"],
    base_stats: { 武力: 35, 智力: 113, 统率: 87, 先攻: 62 },
    innate_skill: {
      season: "S1",
      name: "黄天当立",
      description:
        "准备1回合,对敌军全体造成300%谋略伤害,目标每多一种负面状态,谋略伤害系数提升30%,可提升3次,并使自身获得黄天:发动准备战法时,有50%概率跳过1回合准备，持续4回合",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "张郃",
    faction: "魏",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 104.0, 智力: 81.0, 统率: 101.0, 先攻: 67.0 },
    innate_skill: {
      season: "S1",
      name: "大破街亭",
      description:
        "提升自身2.5%破甲,持续到战斗结束，可叠加4次，然后对敌军随机两人造成220%兵刃伤害,并有65%概率施加缴械持续1回合,若目标已持有缴械状态，则该次伤害提升30%",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "张飞",
    faction: "蜀",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 121.0, 智力: 65.0, 统率: 99.0, 先攻: 81.0 },
    innate_skill: {
      season: "S1",
      name: "万人之敌",
      description:
        "对敌军全体造成140%兵力伤害,并对持有畏惧状态的敌人30%概率造成震慑，持续1回合。未持有畏惧的敌人施加畏惧，持续2回合。",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "徐晃",
    faction: "魏",
    roles: [],
    arms: ["盾兵"],
    base_stats: { 武力: 104, 智力: 81, 统率: 101, 先攻: 67 },
    innate_skill: {
      season: "S1",
      name: "长驱直入",
      description:
        "对敌军随机单体造成350%兵刃伤害,并施加技穷,持续1回合，,若目标已持有技穷状态或是敌军兵力最低单体，则该次伤害值提升30%",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "徐盛",
    faction: "吴",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 89.0, 智力: 87.0, 统率: 107.0, 先攻: 34.0 },
    innate_skill: {
      season: "S1",
      name: "百里疑城",
      description:
        "战斗开始前4回合,我军全体受到伤害前有12.25%概率(受统率影响)获得1层抵御,第4回合开始时,自身统率提升40点,并对敌军全体施加洪水状态，持续2回合",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "文丑",
    faction: "群",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 107, 智力: 50, 统率: 92, 先攻: 77 },
    innate_skill: {
      season: "S1",
      name: "交锋震威",
      description:
        "普通攻击后,获得必中状态,持续2回合,然后对敌军兵力最低单体造成280%兵刃伤害",
      trigger: "追击",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "文聘",
    faction: "魏",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 81.0, 智力: 73.0, 统率: 89.0, 先攻: 25.0 },
    innate_skill: {
      season: "S1",
      name: "扼守荆江",
      description: "使自身统率提升40点，并获得清醒，持续2回合",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "曹仁",
    faction: "魏",
    roles: [],
    arms: ["盾兵"],
    base_stats: { 武力: 81.0, 智力: 79.0, 统率: 113.0, 先攻: 44.0 },
    innate_skill: {
      season: "S1",
      name: "固镇襄樊",
      description:
        "奇数回合自身受到来自后排的伤害降低30%(受统率影响),来自前排的伤害降低7.15%(受统率影响)。偶数回合开始时有37.75%概率对敌军随机两人施加技穷,持续1回合每个目标的概率独立判定",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "曹操",
    faction: "魏",
    roles: [],
    arms: ["盾兵"],
    base_stats: { 武力: 88, 智力: 87, 统率: 86, 先攻: 40 },
    innate_skill: {
      season: "S1",
      name: "乱世建雄",
      description:
        "战斗开始时,使我军全体受到伤害降低14%(受智力影响),获得6%倒戈和攻心(受智力影响)。我军统率最高单体,每次受到伤害后,有30%概率恢复自身兵力(治疗率40%,额外受统率影响)",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "曹洪",
    faction: "魏",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 86.0, 智力: 48.0, 统率: 82.0, 先攻: 54.0 },
    innate_skill: {
      season: "S1",
      name: "八虎雄首",
      description:
        "准备1回合,对敌军随机单体造成360%兵刃和谋略伤害,若目标处于洪水状态该次伤害提升30%",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "李儒",
    faction: "群",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 41, 智力: 114, 统率: 87, 先攻: 59 },
    innate_skill: {
      season: "S1",
      name: "鸩饮毒弑",
      description:
        "对敌军随机两人施加1层鸩毒状态,持续2回合,并使两名队友获得2回合鸩弑:对持有鸩毒状态的目标造成兵刃或谋略伤害后,有50%概率增加目标1层鸩毒状态",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "甄洛",
    faction: "魏",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 22.0, 智力: 103.0, 统率: 103.0, 先攻: 56.0 },
    innate_skill: {
      season: "S1",
      name: "流风回雪",
      description:
        "每个回合开始时,恢复自身兵力(治疗率为140%),并使随机一名队友(优先选择后排)获得洛神:恢复自身兵力(治疗率为140%)，造成伤害提升12.25%,获得洛神后的首次非普通攻击伤害必定触发会心和奇谋。回合结束后洛神消失",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "甘宁",
    faction: "吴",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 112.0, 智力: 84.0, 统率: 107.0, 先攻: 71.0 },
    innate_skill: {
      season: "S1",
      name: "锦帆渠魁",
      description:
        "普通攻击伤害提升140%,普通攻击前提升自身10点武力,持续2回合，可叠加4次",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "皇甫嵩",
    faction: "群",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 88, 智力: 87, 统率: 86, 先攻: 40 },
    innate_skill: {
      season: "S1",
      name: "平乱定叛",
      description:
        "自身统率提升33.3点,自身受到伤害后,有50%概率降低攻击方5.5%造成伤害,持续2回合，可看加4次",
      trigger: "被动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "程昱",
    faction: "魏",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 35, 智力: 113, 统率: 87, 先攻: 62 },
    innate_skill: {
      season: "S1",
      name: "勇冠贲育",
      description:
        "对敌军随机单体造成360%谋略伤害,若目标为前排则额外使目标产生逃兵(受智力影响)",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "程普",
    faction: "吴",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 89, 智力: 87, 统率: 107, 先攻: 34 },
    innate_skill: {
      season: "S1",
      name: "兴王定霸",
      description:
        "我军全体造成兵刃伤害后有60%概率恢复兵力(治疗率40%,额外受统率影响),造成谋略伤害后有60%概率使受到伤害降低14%,持续2回合，可叠加2次",
      trigger: "被动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "荀彧",
    faction: "魏",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 35, 智力: 113, 统率: 87, 先攻: 62 },
    innate_skill: {
      season: "S1",
      name: "建计举人",
      description:
        "我军全体奇谋和看破提升7.15%(受智力影响)。自身造成的恢复效果有17.35%概率(受奇谋影响)触发双倍恢复效果",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "董卓",
    faction: "群",
    roles: [],
    arms: ["盾兵"],
    base_stats: { 武力: 88, 智力: 87, 统率: 86, 先攻: 40 },
    innate_skill: {
      season: "S1",
      name: "权倾朝野",
      description:
        "每个回合行动时夺取敌我全体20点统率，并对敌军全体造成60%兵刃和谋略伤害(额外受统率影响),夺取的统率值在回合结束时返还，夺取效果每个回合下降10%",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "蔡文姬",
    faction: "群",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 22, 智力: 94, 统率: 88, 先攻: 73 },
    innate_skill: {
      season: "S1",
      name: "悲愤诗",
      description:
        "恢复我军兵力最低单体和统率最高单体兵力(治疗率180%),并施加1层抵御。若目标已持有抵御状态,则额外恢复兵力(治疗率60%)",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "袁绍",
    faction: "群",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 80.0, 智力: 92.0, 统率: 105.0, 先攻: 68.0 },
    innate_skill: {
      season: "S1",
      name: "合聚群雄",
      description:
        "每个回合行动时使我军武力/智力/先攻最高单体分别对敌军武力/智力1先攻最低单体造成37.75%兵刃和谋略伤害",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "许褚",
    faction: "魏",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 104, 智力: 81, 统率: 101, 先攻: 67 },
    innate_skill: {
      season: "S1",
      name: "裸衣血战",
      description:
        "战斗开始时,自身先攻和武力提升20点,连击率提升100%,统率降低15点",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "诸葛亮",
    faction: "蜀",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 88, 智力: 87, 统率: 86, 先攻: 40 },
    innate_skill: {
      season: "S1",
      name: "星罗棋布",
      description:
        "指挥战法，发动概率100%，战斗开始时，使我军全体受到谋略伤害降低10%(受智力影响)。选择一种阵型并强化其效果：箕形阵后排增伤提升20%，锥形阵前排增伤提升27%，雁形阵后排增伤提升25%，方圆阵后排连击率提升68%，偃月阵前排增伤提升24%。根据阵型提供额外效果",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "貂蝉",
    faction: "群",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 36, 智力: 118, 统率: 92, 先攻: 53 },
    innate_skill: {
      season: "S1",
      name: "闭月",
      description:
        "自身受到来自异性的伤害降低12.25%(受最高属性影响)。每个回合结束时,令友军武力最高单体兵刃伤害提升7.15%,并对本回合内伤害过貂蝉的目标造成1次22.45%无视统率的兵刃伤害(无法触发会心)",
      trigger: "被动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "赵云",
    faction: "蜀",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 117.0, 智力: 77.0, 统率: 107.0, 先攻: 66.0 },
    innate_skill: {
      season: "S1",
      name: "七进七出",
      description:
        "提升自身17.35%规避率,成功规避后触发龙胆:立刻对敌军随机两人造成90%兵刃伤害,当前回合下一次龙胆的伤害系数降低10%。龙胆每个回合可触发7次",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "邓艾",
    faction: "魏",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 88, 智力: 87, 统率: 86, 先攻: 40 },
    innate_skill: {
      season: "S1",
      name: "屯田令",
      description:
        "战斗开始前3回合,敌我全体造成伤害降低17.35%。每个回合开始时,我军全体受到恢复效果提升10%,可叠加，然后恢复我军全体兵力(治疗率100%)",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "邹氏",
    faction: "群",
    roles: [],
    arms: ["盾兵"],
    base_stats: { 武力: 23, 智力: 89, 统率: 61, 先攻: 24 },
    innate_skill: {
      season: "S1",
      name: "顾盼生姿",
      description:
        "战斗开始时,我军全体获得顾盼:受到的伤害、追击战法伤害、主动战法伤害降低16%。邹氏受到兵刃伤害后有60%概率使我军全体顾盼效果降低2%，最多降低8次。第4回合起，每回合恢复我军随机两人兵力(治疗率140%)",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "郭嘉",
    faction: "魏",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 35, 智力: 113, 统率: 87, 先攻: 62 },
    innate_skill: {
      season: "S1",
      name: "算无遗策",
      description:
        "战斗开始时,提升自身及智力最高友军6%主动战法发动率。自身成功发动主动战法后,有60%概率额外再发动一次(准备战法不需要再次准备)",
      trigger: "指挥",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "钟繇",
    faction: "魏",
    roles: [],
    arms: ["弓兵"],
    base_stats: { 武力: 35, 智力: 113, 统率: 87, 先攻: 62 },
    innate_skill: {
      season: "S1",
      name: "飞鸿戏海",
      description:
        "对敌军全体造成110%谋略伤害,并提升自身10%看破,持续2回合，可叠加2次",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "颜良",
    faction: "群",
    roles: [],
    arms: ["枪兵"],
    base_stats: { 武力: 107.0, 智力: 50.0, 统率: 92.0, 先攻: 77.0 },
    innate_skill: {
      season: "S1",
      name: "膂力过人",
      description:
        "普通攻击后,对当前攻击目标造成150%兵刃伤害,若目标武力低于自身额外造成70%兵刃伤害",
      trigger: "追击",
      probability: 1.0,
    },
  },
  {
    season: "S1",
    name: "马超",
    faction: "蜀",
    roles: [],
    arms: ["骑兵"],
    base_stats: { 武力: 118.0, 智力: 58.0, 统率: 103.0, 先攻: 75.0 },
    innate_skill: {
      season: "S1",
      name: "纵马横枪",
      description:
        "提升自身22.45%会心几率,造成会心伤害后对目标发动追伤:造成1次60%无视统率的兵刃伤害(无法触发会心)。若目标持有负面状态追伤伤害提升20%,追伤每个回合可触发5次",
      trigger: "主动",
      probability: 1.0,
    },
  },
  {
    season: "S2",
    name: "法正",
    faction: "蜀",
    roles: ["辅助", "后排"],
    arms: ["弓兵"],
    base_stats: { 武力: 51.0, 智力: 99.0, 统率: 82.0, 先攻: 75.0 },
    innate_skill: {
      season: "S2",
      name: "睹事知机",
      description:
        "对敌军全体施加事：下一次受到非普通攻击伤害后为攻击者恢复兵力（治疗率40%→80%，受智力影响），并额外受到来自法正的60%→120%谋略伤害",
      trigger: "主动",
      probability: 1,
    },
  },
  {
    season: "S2",
    name: "张辽",
    faction: "魏",
    roles: ["兵刃", "前排"],
    arms: ["骑兵"],
    base_stats: { 武力: 80.0, 智力: 95.0, 统率: 135.0, 先攻: 35.0 },
    innate_skill: {
      season: "S2",
      name: "风袭逍遥",
      description:
        "破甲提升10%→20%。每个回合开始时有60%→60%概率（受已损失兵力影响）获得1回合清醒。若自身为前排，造成伤害后对敌军随机单体造成25%→50%的传递伤害，优先选择后排目标",
      trigger: "被动",
      probability: 1,
    },
  },
    {
    season: "S2",
    name: "鲁肃",
    faction: "吴",
    roles: ["辅助", "均衡"],
    arms: ["枪兵"],
    base_stats: { 武力: 70.0, 智力: 97.0, 统率: 89.0, 先攻: 69.0 },
    innate_skill: {
      season: "S2",
      name: "划湘分荆",
      description:
        "对敌我全体随机4个目标施加缴械，持续1回合。若选中我方目标，则使目标受到伤害降低10%→20%（受智力影响），持续1回合；若选中敌方目标，则使目标受到伤害提升10%→20%（受智力影响）持续1回合",
      trigger: "主动",
      probability: 0.45,
    },
  },
    {
    season: "S2",
    name: "陆逊",
    faction: "吴",
    roles: ["谋略", "后排"],
    arms: ["弓兵"],
    base_stats: { 武力: 65.0, 智力: 103.0, 统率: 93.0, 先攻: 39.0 },
    innate_skill: {
      season: "S2",
      name: "火烧连营",
      description:
        "对敌军随机单体施加火攻，持续2回合，然后对已持有火攻状态的敌军目标施加1层焚烧状态，持续2回合，同时造成110%→220%谋略伤害，并有40%概率（受智力影响）额外施加1层焚烧状态",
      trigger: "主动",
      probability: 0.33,
    },
  },
    {
    season: "S2",
    name: "陈宫",
    faction: "群",
    roles: ["辅助", "均衡"],
    arms: ["弓兵"],
    base_stats: { 武力: 52.0, 智力: 97.0, 统率: 76.0, 先攻: 63.0 },
    innate_skill: {
      season: "S2",
      name: "智令从计",
      description:
        "每个回合开始时，使我军武力最高单体获得1回合从计：受到谋略伤害降低7.5%→15%（受智力影响），发动追击战法后对敌军随机单体造成70%→140%谋略伤害（受目标武力影响）",
      trigger: "指挥",
      probability: 1,
    },
  },
    {
    season: "S2",
    name: "田丰",
    faction: "群",
    roles: ["辅助", "后排"],
    arms: ["弓兵"],
    base_stats: { 武力: 49.0, 智力: 83.0, 统率: 64.0, 先攻: 65.0 },
    innate_skill: {
      season: "S2",
      name: "荐计阻敌",
      description:
        "使我军统率最高单体获得1层抵御，武力，智力，先攻提升20→40点（受最高属性影响），使敌军统率最低单体武力，智力，先攻降低20→40点（受最高属性影响），持续2回合",
      trigger: "主动",
      probability: 0.6,
    },
  },
    {
    season: "S1",
    name: "徐庶",
    faction: "蜀",
    roles: ["文武", "后排"],
    arms: ["弓兵"],
    base_stats: { 武力: 85.0, 智力: 96.0, 统率: 85.0, 先攻: 75.0 },
    innate_skill: {
      season: "S1",
      name: "折节学问",
      description:
        "对敌军随机单体造成110%→220%谋略和兵刃伤害。若目标武力大于智力，则造成缴械，反之造成技穷，持续1回合",
      trigger: "主动",
      probability: 0.65,
    },
  },
    {
    season: "S1",
    name: "贾诩",
    faction: "魏",
    roles: ["谋略", "后排"],
    arms: ["骑兵"],
    base_stats: { 武力: 57.0, 智力: 106.0, 统率: 80.0, 先攻: 55.0 },
    innate_skill: {
      season: "S1",
      name: "诡道玄机",
      description:
        "每个回台开始时有90%→90%概率对故车随机单体和一名队发施加混乱，持续2回合，若敌军目标已持有混乱状态，则额外造成150%→300%谋略伤害，若友军目标已持有混乱状态，则额外恢复其和自身兵力（治疗率55%→110%，受智力影响）我军全体对自身和友军造成的伤害降低30%→60%",
      trigger: "指挥",
      probability: 1,
    },
  },
    {
    season: "S1",
    name: "黄盖",
    faction: "吴",
    roles: ["谋略", "后排"],
    arms: ["枪兵"],
    base_stats: { 武力: 86.0, 智力: 83.0, 统率: 102.0, 先攻: 73.0 },
    innate_skill: {
      season: "S1",
      name: "苦肉计",
      description:
        "自身受到伤害降低15%→30%（受统率影响），持续2回合。令智力最高友军对自身造成30%→60%兵刃伤害，对敌军随机两人造成110%→220%谋略伤害，并施加火攻，持续2回合",
      trigger: "主动",
      probability: 0.5,
    },
  },
    {
    season: "S2",
    name: "英雄张角",
    faction: "群",
    roles: ["辅助", "防御", "前排"],
    arms: ["盾兵"],
    base_stats: { 武力: 32.0, 智力: 89.0, 统率: 95.0, 先攻: 74.0 },
    innate_skill: {
      season: "S2",
      name: "承天太平",
      description:
        "自身受到伤害降低18.06%→25%（受智力影响），每个回合行动时有36.11%→50%概率（受智力影响）驱散两名队友随机1种负面状态，并使其造成伤害提升18.06%→25%（受智力影响），持续2回合",
      trigger: "指挥",
      probability: 1,
    },
  },
    {
    season: "S2",
    name: "英雄张梁",
    faction: "群",
    roles: ["防御", "兵刃", "前排"],
    arms: ["盾兵"],
    base_stats: { 武力: 94.0, 智力: 44.0, 统率: 99.0, 先攻: 62.0 },
    innate_skill: {
      season: "S2",
      name: "嫉恶如仇",
      description:
        "自身倒戈提升12.5%→25%，持续2回合，可叠加4次，然后对敌军随机两人造成120%→240%兵刃伤害，嫉恶如仇发动率大于80%时，自身额外获得25%规避率，持续2回合，每一次释放嫉恶如仇后，嫉恶如仇发动率提升6%，可叠加",
      trigger: "主动",
      probability: 0.65,
    },
  },
    {
    season: "S2",
    name: "英雄张宝",
    faction: "群",
    roles: ["辅助", "治疗", "后排"],
    arms: ["盾兵"],
    base_stats: { 武力: 64.0, 智力: 79.0, 统率: 90.0, 先攻: 76.0 },
    innate_skill: {
      season: "S2",
      name: "守明却灾",
      description:
        "提升两名队友25%→50%会心和奇谋几率，若友军兵力低于最大兵力的70%额外使其受到伤害降低7.5%→15%（受智力影响），持续2回合，并恢复其兵力（治疗率150%→300%）",
      trigger: "主动",
      probability: 0.65,
    },
  },
];
