export const zhanfaData = [
  {
    season: "S1",
    name: "一计决胜",
    type: "主动",
    probability: 0.35,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "准备1回合，对敌军随机两人造成110%谋略伤害，并施加虛弱状态,持续2回合，若目标已持有虛弱状态，则额外造成25%谋略伤害",
  },
  {
    season: "S1",
    name: "万夫莫当",
    type: "被动",
    probability: 1.0,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "普通攻击后，有60%概率对攻击目标的两名队友造成该次普通攻击50％的传递伤害，若自身武力高于目标，则额外造成15%兵刃伤害",
  },
  {
    season: "S1",
    name: "上兵伐谋",
    type: "主动",
    probability: 0.4,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军智力最低单体",
    description: "对敌军智力最低单体造成120%谋略伤害，并使其智力降低15点(受智力影响)，持续2回合，可叠加2次",
  },
  {
    season: "S1",
    name: "上智为间",
    type: "主动",
    probability: 0.35,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "对敌军随机两人施加混乱，持续1回合，并使其受到伤害提升7.5%(受智力影响)，持续2回合",
  },
  {
    season: "S1",
    name: "临危勇烈",
    type: "主动",
    probability: 0.45,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "自身获得1层抵御，并提升20点武力，持续2回合，然后对敌军随机单体造成120%兵刃伤害",
  },
  {
    season: "S1",
    name: "临阵突袭",
    type: "主动",
    probability: 0.45,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成120%兵刃伤害，并有50%概率使其缴械，持续1回合",
  },
  {
    season: "S1",
    name: "乘虚而入",
    type: "主动",
    probability: 0.4,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军统率最低单体",
    description: "对敌军统率最低单体造成120%兵刃伤害，并使其统率降低15点(受武力影响)，持续2回合，可叠加2次",
  },
  {
    season: "S1",
    name: "乱敌方阵",
    type: "主动",
    probability: 0.35,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成60%兵刃伤害，并有35%概率使其混乱，持续1回合",
  },
  {
    season: "S1",
    name: "五雷轰顶",
    type: "主动",
    probability: 0.45,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "准备1回合，对敌军随机单体造成5次谋略伤害(伤害率45%)，每次目标独立判定",
  },
  {
    season: "S1",
    name: "以战养战",
    type: "主动",
    probability: 0.45,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成120%兵刃伤害，并恢复自身兵力(治疗率60%，受武力影响)",
  },
  {
    season: "S1",
    name: "以静制动",
    type: "主动",
    probability: 0.4,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "自身受到伤害降低10%，持续2回合，并获得反击状态(伤害率40%)，持续2回合",
  },
  {
    season: "S1",
    name: "任人择势",
    type: "主动",
    probability: 0.45,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "提升自身15点武力和智力，持续2回合，并使自身下一次主动战法伤害提升20%",
  },
  {
    season: "S1",
    name: "伏兵四起",
    type: "主动",
    probability: 0.4,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "准备1回合，对敌军全体造成70%谋略伤害，并施加中毒状态，持续2回合",
  },
  {
    season: "S1",
    name: "克敌如风",
    type: "主动",
    probability: 0.5,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成120%兵刃伤害，并施加风暴，持续2回合",
  },
  {
    season: "S6",
    name: "兵贵神速",
    type: "追击",
    probability: 0.4,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "普通攻击后，对敌军随机单体造成120%->133.3%兵刃伤害，并使自身先攻提升15->16.6点(受武力影响)，持续2回合",
  },
  {
    season: "S1",
    name: "决水破敌",
    type: "主动",
    probability: 0.6,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "对敌军随机两人造成50%谋略伤害，并施加洪水，持续2回合",
  },
  {
    season: "S1",
    name: "出其不意",
    type: "主动",
    probability: 0.55,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成175%谋略伤害，若目标持有负面状态，则该次伤害提升12.5%",
  },
  {
    season: "S1",
    name: "势如破竹",
    type: "主动",
    probability: 0.275,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "提升自身10%会心几率，持续2回合，然后对敌军全体造成70%兵刃伤害",
  },
  {
    season: "S1",
    name: "勇冠三军",
    type: "被动",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "自身倒戈提升15%，并使自身造成兵刃伤害提升3%，可叠加6次，持续到战斗结束",
  },
  {
    season: "S1",
    name: "千里突袭",
    type: "追击",
    probability: 0.4,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成140%兵刃伤害，若目标为后排，则额外造成50%兵刃伤害",
  },
  {
    season: "S1",
    name: "咏歌尝酒",
    type: "主动",
    probability: 0.65,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "恢复我军随机两人兵力(治疗率65%，受智力影响)，并提升其8点统率，持续2回合",
  },
  {
    season: "S1",
    name: "坚壁清野",
    type: "主动",
    probability: 0.5,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "嘲讽敌军全体，并提升自身18点统率，持续2回合",
  },
  {
    season: "S1",
    name: "坚如磐石",
    type: "主动",
    probability: 0.55,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "嘲讽敌军全体，并使自身受到伤害降低15%，持续2回合",
  },
  {
    season: "S1",
    name: "夜袭",
    type: "追击",
    probability: 0.45,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "对敌军随机两人造成60%兵刃伤害，若自身先攻大于目标，则额外造成25%兵刃伤害",
  },
  {
    season: "S1",
    name: "奇计迭出",
    type: "追击",
    probability: 0.4,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成125%谋略伤害，优先选择敌军后排",
  },
  {
    season: "S1",
    name: "奇门遁甲",
    type: "主动",
    probability: 0.4,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "准备1回合，对敌军全体造成125%谋略伤害，并有6%概率施加震慑，持续1回合",
  },
  {
    season: "S1",
    name: "如有神助",
    type: "被动",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "主动战法发动率提升4%，主动战法伤害提升3.5%",
  },
  {
    season: "S1",
    name: "如沐春风",
    type: "被动",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机单体",
    description: "每回合行动时，有40%概率恢复我军随机单体兵力(治疗率50%，受智力影响)",
  },
  {
    season: "S1",
    name: "威名显赫",
    type: "主动",
    probability: 0.275,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成60%兵刃伤害，并使其受到伤害提升7.5%，持续2回合",
  },
  {
    season: "S1",
    name: "屈人之兵",
    type: "主动",
    probability: 0.22,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成140%谋略伤害，并使其智力降低15点(受智力影响)，持续2回合",
  },
  {
    season: "S1",
    name: "巧利天灾",
    type: "主动",
    probability: 0.5,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成60%谋略伤害，并有35%概率使其随机获得1种控制状态，持续1回合",
  },
  {
    season: "S1",
    name: "强袭",
    type: "主动",
    probability: 0.45,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成120%兵刃伤害，并使其受到兵刃伤害提升10%，持续2回合",
  },
  {
    season: "S1",
    name: "忘私相助",
    type: "被动",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机单体",
    description: "恢复我军随机单体兵力(治疗率80%，受智力影响)，并使其受到伤害降低10%，持续2回合",
  },
  {
    season: "S1",
    name: "战八方",
    type: "主动",
    probability: 0.55,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成75%兵刃伤害，并有35%概率使其受到伤害提升7.5%，持续2回合",
  },
  {
    season: "S1",
    name: "披坚执锐",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "自身受到伤害降低10%，并提升15点统率，持续2回合",
  },
  {
    season: "S1",
    name: "指点乾坤",
    type: "主动",
    probability: 0.5,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "令我军武力最高单体对敌军全体造成40%兵刃伤害，令我军智力最高单体对敌军全体造成40%谋略伤害",
  },
  {
    season: "S1",
    name: "揭竿而起",
    type: "主动",
    probability: 1.0,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "对敌军随机两人造成75%兵刃伤害，并施加断粮，持续1回合",
  },
  {
    season: "S1",
    name: "攻其不备",
    type: "追击",
    probability: 0.4,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "攻击目标",
    description: "对攻击目标造成140%兵刃伤害，并施加技穷，持续1回合",
  },
  {
    season: "S1",
    name: "文武双全",
    type: "主动",
    probability: 0.65,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军单体",
    description: "对敌军武力最高单体造成110%谋略伤害，对敌军智力最高单体造成110%兵刃伤害",
  },
  {
    season: "S1",
    name: "文治武功",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "每回合行动时，有30%概率对敌军随机两人造成50%兵刃和谋略伤害",
  },
  {
    season: "S1",
    name: "料事如神",
    type: "主动",
    probability: 0.45,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "对敌军随机两人造成90%谋略伤害，并有25%概率使其技穷，持续1回合",
  },
  {
    season: "S1",
    name: "斩将夺旗",
    type: "主动",
    probability: 0.55,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军单体",
    description: "对敌军统率最低单体造成110%兵刃伤害，并施加断粮，持续2回合",
  },
  {
    season: "S1",
    name: "断敌粮道",
    type: "指挥",
    probability: 1.0,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军单体",
    description: "每回合开始时，对敌军随机单体施加断粮，持续2回合，并造成55%谋略伤害",
  },
  {
    season: "S1",
    name: "无难之志",
    type: "主动",
    probability: 0.385,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "提升我军随机两人11.2%连击率和10%倒戈，持续2回合",
  },
  {
    season: "S1",
    name: "束手无策",
    type: "主动",
    probability: 0.45,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成100%谋略伤害，并施加技穷，持续1回合",
  },
  {
    season: "S1",
    name: "来好息师",
    type: "被动",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军全体",
    description: "每回合结束时，恢复我军前排兵力(治疗率45%，受智力影响)",
  },
  {
    season: "S1",
    name: "横征暴敛",
    type: "被动",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "施加负面状态后，恢复自身兵力(治疗率20%，受统率影响)，并使自身受到伤害降低5%，持续2回合，可叠加4次",
  },
  {
    season: "S1",
    name: "横扫千军",
    type: "追击",
    probability: 0.45,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成60%兵刃伤害，且每成功发动一次，该次伤害提升6%，可叠加5次",
  },
  {
    season: "S1",
    name: "水淹七军",
    type: "主动",
    probability: 0.4,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "准备1回合，对敌军全体造成130%兵刃伤害，并施加洪水，持续2回合",
  },
  {
    season: "S1",
    name: "洞若观火",
    type: "主动",
    probability: 0.5,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机单体",
    description: "恢复我军随机单体兵力(治疗率130%，受智力影响)，并使其获得洞察，持续2回合",
  },
  {
    season: "S1",
    name: "清风驱疾",
    type: "主动",
    probability: 0.6,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "驱散我军随机两人1种负面状态，并恢复其兵力(治疗率90%，受智力影响)",
  },
  {
    season: "S1",
    name: "火羽",
    type: "主动",
    probability: 0.4,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成75%兵刃伤害，并施加火攻，持续2回合",
  },
  {
    season: "S1",
    name: "烈火焚营",
    type: "主动",
    probability: 0.45,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成40%谋略伤害，并施加火攻，持续2回合，再进行3次焚营：对敌军随机单体造成40%谋略伤害",
  },
  {
    season: "S1",
    name: "狂风大作",
    type: "指挥",
    probability: 1.0,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "第2、4回合开始时，敌我全体陷入风暴，持续2回合。奇数回合开始时，有60%概率对全体敌军造成50%谋略伤害，偶数回合开始时，有60%概率对敌军随机单体造成140%谋略伤害",
  },
  {
    season: "S1",
    name: "王佐之才",
    type: "被动",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "自身奇谋提升10%(受智力影响)，造成谋略伤害后，有50%概率提升自身5点智力(受智力影响)，持续2回合，可叠加4次",
  },
  {
    season: "S1",
    name: "疾行侧击",
    type: "主动",
    probability: 0.6,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成75%兵刃伤害，并施加畏惧，持续2回合，施放2次",
  },
  {
    season: "S1",
    name: "百战不殆",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军单体",
    description: "我军最高属性单体受到伤害时，有60%概率提升其1.8点最高属性，可叠加8次，持续到战斗结束",
  },
  {
    season: "S1",
    name: "破军袭敌",
    type: "主动",
    probability: 0.5,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "准备1回合，对敌军全体造成150%兵刃伤害",
  },
  {
    season: "S1",
    name: "破阵驰围",
    type: "主动",
    probability: 0.6,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "准备1回合，使敌军随机单体受到伤害提升15%，持续2回合，然后对其造成220%兵刃伤害",
  },
  {
    season: "S1",
    name: "筹划良策",
    type: "主动",
    probability: 0.5,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "提升自身10点智力，持续2回合，并对敌军随机两人造成80%谋略伤害",
  },
  {
    season: "S1",
    name: "舍生取义",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军全体",
    description: "战斗开始前2回合，我军全体连击率提升15%，我军武力最高单体获得洞察，自身获得震慑，持续2回合",
  },
  {
    season: "S1",
    name: "蓄势待发",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "每回合开始时，提升我军随机两人1.8%造成伤害，可叠加，持续到战斗结束",
  },
  {
    season: "S1",
    name: "计袭粮仓",
    type: "追击",
    probability: 0.45,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对攻击目标造成150%谋略伤害，并施加断粮，持续2回合，若目标已持有断粮，则额外造成50%谋略伤害",
  },
  {
    season: "S1",
    name: "计逐穷寇",
    type: "被动",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "造成谋略伤害后，有30%概率对敌军随机单体造成1次普通攻击，每回合最多触发1次",
  },
  {
    season: "S1",
    name: "谈笑诛心",
    type: "被动",
    probability: 1.0,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "敌军被施加负面状态时，有30%概率对敌军随机单体造成55%谋略伤害，每回合最多触发2次",
  },
  {
    season: "S1",
    name: "趁火打劫",
    type: "主动",
    probability: 0.5,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "准备1回合，对敌军随机两人造成110%谋略和兵刃伤害，若目标处于火攻，则额外施加混乱，持续2回合",
  },
  {
    season: "S1",
    name: "轻装驰援",
    type: "追击",
    probability: 0.275,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "提升我军随机两人11.2%连击率，持续2回合，并使其受到伤害降低10%，持续2回合",
  },
  {
    season: "S1",
    name: "辕门射戟",
    type: "追击",
    probability: 0.7,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成150%兵刃伤害，优先选择后排，若目标为后排，则额外造成50%兵刃伤害",
  },
  {
    season: "S1",
    name: "迎敌",
    type: "主动",
    probability: 0.5,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "嘲讽敌军全体，并使自身受到伤害降低10%，持续2回合",
  },
  {
    season: "S1",
    name: "运筹帷幄",
    type: "主动",
    probability: 0.45,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "提升自身10点智力，持续2回合，并使自身下一次主动战法伤害提升20%",
  },
  {
    season: "S1",
    name: "避其锐气",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "使敌军随机两人造成伤害降低10%，持续2回合",
  },
  {
    season: "S1",
    name: "铁骑横冲",
    type: "追击",
    probability: 0.4,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成60%兵刃伤害，并使其受到兵刃伤害提升7.5%，持续2回合",
  },
  {
    season: "S1",
    name: "铸甲销戈",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "恢复我军随机两人兵力(治疗率65%，受智力影响)，并使其受到伤害降低10%，持续2回合",
  },
  {
    season: "S1",
    name: "锐不可当",
    type: "被动",
    probability: 1.0,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "自身破甲提升7.5%，持续2回合，然后对敌军随机单体造成120%兵刃伤害",
  },
  {
    season: "S1",
    name: "青囊急救",
    type: "主动",
    probability: 0.55,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "受到伤害后，有50%概率恢复自身兵力(治疗率60%，受智力影响)，每回合最多触发3次",
  },
  {
    season: "S1",
    name: "风卷残云",
    type: "主动",
    probability: 1.0,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成60%兵刃伤害，并有35%概率使其随机获得1种控制状态，持续1回合",
  },
  {
    season: "S1",
    name: "骁勇之姿",
    type: "主动",
    probability: 0.45,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "提升自身15点武力，持续2回合，并使自身下一次主动战法伤害提升20%",
  },
  {
    season: "S2",
    name: "摧坚克难",
    type: "被动",
    probability: 1.0,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "提升自身20%会心几率，每个回合行动结束时对敌军随机两人造成55％兵刃伤害",
  },
  {
    season: "S2",
    name: "知人善任",
    type: "主动",
    probability: 0.75,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军智力最高单体",
    description: "使我军智力最高单体受到伤害降低12.5%(受智力影响），持续2回合，并获得1层抵御",
  },
  {
    season: "S2",
    name: "乘间投隙",
    type: "追击",
    probability: 0.6,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "普通攻击后，对敌军随机单体施加混乱，持续1回合，并造成60%谋略伤害,若目标已处于混乱状态，则对其友军随机单体造成50%谋略伤害",
  },
  {
    season: "S1",
    name: "韬光养晦",
    type: "被动",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "自身主动战法发动率提升3%，且造成谋略伤害提升5%，持续2回合，可叠加4次",
  },
  {
    season: "S2",
    name: "任人唯贤",
    type: "主动",
    probability: 0.6,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "提升我军随机两人7.5%造成伤害,12.5点统率，持续2回合",
  },
  {
    season: "S2",
    name: "穷追不舍",
    type: "被动",
    probability: 1.0,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "每个回合行动时有60%概率对持有异常状态的敌军造成60%兵刃伤害，每个目标独立判定",
  },
  {
    season: "S2",
    name: "三军夺气",
    type: "追击",
    probability: 0.55,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "普通攻击后，使攻击目标武力、智力、统率降低15点，持续2回合，最多可叠加5次",
  },
  {
    season: "S2",
    name: "固若金汤",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "自身统率提升7.5%，第2回合起，每个回合开始时有30%概率(受统率影响）嘲讽敌军随机两人，持续2回合",
  },
  {
    season: "S2",
    name: "胜敌益强",
    type: "被动",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "造成兵刃伤害后提升自身8点武力，可叠加8次，造成谋略伤害后提升自身8点智力，可叠加8次",
  },
  {
    season: "S2",
    name: "奇计良谋",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "战斗开始前3回合，使敌军武力最高单体造成的兵刃伤害降低14%->15.5%（受智力影响），使敌军智力最高单体造成的谋略伤害降低14%->15.5%（受智力影响）",
  },
  {
    season: "S2",
    name: "兵不厌诈",
    type: "主动",
    probability: 0.35,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "对敌军随机两人造成70%->77.7%谋略伤害，并有35%->38.8%概率使其随机获得1种控制状态，持续1回合",
  },
  {
    season: "S2",
    name: "战必断金",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "战斗开始前3回合，使敌军随机两人有45%->50%概率陷入怯战状态，无法进行普通攻击",
  },
  {
    season: "S2",
    name: "避其锋芒",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "战斗开始前3回合，使我军随机两人受到伤害降低15%->16.6%（受智力影响）",
  },
  {
    season: "S2",
    name: "妖术",
    type: "主动",
    probability: 0.5,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成70%->77.7%谋略伤害，并施加妖术持续2回合，若目标已持有妖术状态则额外使其造成伤害降低8%->8.8%，持续1回合",
  },
  {
    season: "S2",
    name: "浑水摸鱼",
    type: "主动",
    probability: 0.35,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "准备1回合，使敌军全体随机获得1种控制状态，持续2回合",
  },
  {
    season: "S2",
    name: "绝水遏敌",
    type: "主动",
    probability: 0.5,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成75%->83.3%谋略伤害，并有75%概率施加断粮，持续1回合",
  },
  {
    season: "S2",
    name: "始计",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "战斗开始前3回合，自身受到伤害后，有50%概率使自身获得洞察，持续1回合，并使自身下一次主动战法伤害提升20%->22.2%",
  },
  {
    season: "S2",
    name: "鹤翼",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军全体",
    description: "战斗开始前3回合，我军全体获得分兵（伤害率35%->38.8%），但受到伤害提升10%",
  },
  {
    season: "S2",
    name: "迷阵",
    type: "主动",
    probability: 0.35,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成120%->133.3%谋略伤害，并使其混乱，持续1回合",
  },
  {
    season: "S2",
    name: "落雷",
    type: "主动",
    probability: 0.35,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成140%->155.5%谋略伤害，并使其受到谋略伤害提升10%，持续2回合",
  },
  {
    season: "S2",
    name: "空城计",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "战斗开始前2回合，使自身受到伤害降低20%->22.2%，并获得洞察，持续2回合",
  },
  {
    season: "S2",
    name: "步步为营",
    type: "被动",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "自身受到伤害降低4.5%->5%，持续到战斗结束，可叠加8次",
  },
  {
    season: "S6",
    name: "奇正相生",
    type: "指挥",
    probability: 1.0,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人/敌军随机两人",
    description: "第2回合起，回合开始时，有65%概率恢复我军随机两人兵力(治疗率为75%，受智力影响），回合结束时，有65%概率对敌军随机两人造成75%谋略伤害",
  },
  {
    season: "S6",
    name: "威震华夏",
    type: "主动",
    probability: 0.35,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "准备1回合，对敌军全体造成130%->144.4%兵刃伤害，并有40%->44.4%概率使目标随机获得1种控制状态，持续2回合",
  },
  {
    season: "S6",
    name: "空城计",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌我全体",
    description: "战斗开始前3回合，敌我全体主动战法发动率降低7%->7.7%（受智力影响）第4回合开始时，我军智力最高单体造成谋略伤害提升8%->8.8%（受智力影响），我军智力最低单体受到谋略伤害降低8%->8.8％（受智力影响）",
  },
  {
    season: "S1",
    name: "借东风",
    type: "主动",
    probability: 0.4,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体施加风暴状态，持续2回合。使敌方全体任意一人受到负面状态时，为其友军施加相同的负面状态，若该友军已持有此状态，则造成80%谋略伤害",
  },
  {
    season: "S1",
    name: "一鼓作气",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军全体",
    description: "战斗开始前3回合，我军全体造成伤害提升25%，第4回合起造成伤害降低15%",
  },
  {
    season: "S3",
    name: "金城汤池",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军全体",
    description: "回合开始时我军全体有40%-44.4%概率获得1层抵御，每个回合概率降低12％",
  },
  {
    season: "S6",
    name: "步步为营",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身及随机友军",
    description: "每回合开始时，有60%概率使自身及随机友军单体受到的伤害降低12%->13.3%（受统率影响），持续1回合，每回合触发概率提升5%->5.5%，每个武将独立判断",
  },
  {
    season: "S5",
    name: "挫锐折锋",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军单体",
    description: "战斗开始前3回合，敌军武力最高单体造成兵刃伤害降低12.5%-13.8%（受统率影响），敌军智力最高单体造成谋略伤害降低12.5% 13.8%（受统率影响）",
  },
  {
    season: "S5",
    name: "运智铺谋",
    type: "被动",
    probability: 1.0,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "普通攻击后，谋略伤害提升3.5%->3.8%，可叠加5次。造成谋略伤害后，有25%->27.7%概率对敌军随机单体造成1次普通攻击，每个回合最多触发1次",
  },
  {
    season: "S5",
    name: "十面埋伏",
    type: "主动",
    probability: 0.45,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成75%->83.3%兵刃伤害，并有75%概率施加断粮，持续1回合",
  },
  {
    season: "S7",
    name: "谋而后动",
    type: "追击",
    probability: 0.75,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "普通攻击后,对敌军全体造成20%→22.2%谋略伤害，有50%概率(受智力影响)额外再发动一次谋而后动(无法再次发动)，谋而后动的伤害系数每回合提升6%→6.6%",
  },
  {
    season: "S7",
    name: "黄天惑心",
    type: "主动",
    probability: 0.55,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌方全体",
    description: "对敌方全体造成70%→77.7%的谋略伤害，并施加妖术持续2回合，若目标已持有妖术状态则额外使其造成伤害降低8%→8.8%，持续1回合",
  },
  {
    season: "S7",
    name: "断戈夺锋",
    type: "主动",
    probability: 0.5,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "对敌军随机两人造成110%→122.2%兵刃伤害，并有37.5%→41.6%概率施加缴械，持续1回合",
  },
  {
    season: "S4",
    name: "折冲御侮",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "战斗开始前3回合，我军随机两人受到伤害降低12%->13.3%（受智力影响），并在第4回合开始时为我军全体恢复兵力（治疗率180%->200%，受智力影响）",
  },
  {
    season: "S3",
    name: "明其虚实",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "战斗开始前3回合，使敌军随机两人受到伤害提升12%->13.3%（受智力影响）",
  },
  {
    season: "S3",
    name: "烈火张天",
    type: "主动",
    probability: 0.45,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成60%->66.6%谋略伤害，并施加火攻，持续2回合，若目标已持有火攻状态，则额外造成40%->44.4%谋略伤害",
  },
  {
    season: "S8",
    name: "惩前毖后",
    type: "指挥",
    probability: 1.0,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人/我军前排",
    description: "每个回合开始时，对敌军随机两人造成45%→50%谋略伤害(额外受全队累积治疗量影响)。每个回合结束时，恢复我军前排兵力(治疗率25%→27.7%，受智力影响)",
  },
  {
    season: "S8",
    name: "神略制变",
    type: "主动",
    probability: 1.0,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人/敌军随机两人",
    description: "前4回合发动时，恢复我军随机两人兵力(治疗率55%→61.1%，受智力影响)后4回合发动时，对敌军随机两人造成80%→88.8%谋略伤害",
  },
  {
    season: "S8",
    name: "万军辟易",
    type: "追击",
    probability: 0.35,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "普通攻击后，对敌军全体造成70%→77.7%兵刃伤害，偶数回合发动时额外对敌军兵力最低单体造成50%55.5%兵刃伤害，若上个回合没有发动，该次战法伤害提升50%",
  },
  {
    season: "S9",
    name: "御敌临前",
    type: "主动",
    probability: 0.75,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "使自身和一名随机队友受到伤害降低10%→11.1%(受先攻影响),持续1回合，若自身为前排，额外恢复自身兵力(治疗率60%→66.6%，受智力和先攻影响",
  },
  {
    season: "S9",
    name: "虎步连环",
    type: "追击",
    probability: 0.5,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "普通攻击后，对敌军随机两人造成55%→61.1%兵刃伤害并有30%→33.3%概率使目标随机获得1种控制状态，持续1回合，每个目标独立判定",
  },
  {
    season: "S11",
    name: "掠阵破军",
    type: "主动",
    probability: 0.45,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成75%->83.3%兵刃伤害，并有75%概率施加断粮，持续1回合",
  },
  {
    season: "S11",
    name: "及锋而试",
    type: "主动",
    probability: 0.6,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成120%->133.3%兵刃伤害，若目标兵力低于50%，则额外造成60%->66.6%兵刃伤害",
  },
  {
    season: "S11",
    name: "调和阴阳",
    type: "主动",
    probability: 0.5,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "恢复我军随机两人兵力（治疗率100%->111.1%，受智力影响），并使其受到伤害降低10%->11.1%，持续1回合",
  },
  {
    season: "S10",
    name: "蹈锋饮血",
    type: "主动",
    probability: 0.5,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "对敌军随机两人造成110%->122.2%兵刃伤害，并恢复自身兵力（治疗率60%->66.6%，受武力影响）",
  },
  {
    season: "S10",
    name: "践墨随敌",
    type: "主动",
    probability: 0.5,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "对敌军随机两人造成70%->77.7%谋略伤害，并有35%->38.8%概率使其随机获得1种控制状态，持续1回合",
  },
  {
    season: "S10",
    name: "机变无穷",
    type: "主动",
    probability: 0.45,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "对敌军随机两人造成70%->77.7%谋略伤害，并夺取其10->11.1点智力、统率（受智力影响），持续2回合",
  },
  {
    season: "S9",
    name: "潜龙在渊",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军全体",
    description: "战斗开始前3回合，我军全体造成主动战法伤害提升15%->16.6%，第4回合起，我军全体受到主动战法伤害降低15%->16.6%",
  },
  {
    season: "S1",
    name: "追亡逐北",
    type: "主动",
    probability: 0.6,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成120%兵刃伤害，若目标兵力低于50%，则额外造成60%兵刃伤害",
  },
  {
    season: "S4",
    name: "文韬武略",
    type: "追击",
    probability: 0.32,
    traitType: "文武",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军单体",
    description: "普通攻击后，对敌军智力最低单体造成80%->88.8%谋略伤害，对敌军统率最低单体造成80%->88.8%兵刃伤害",
  },
  {
    season: "S4",
    name: "洗筋伐髓",
    type: "被动",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "回合开始时，使自身造成伤害提升5%->5.5%，可叠加3次，持续到战斗结束。回合行动时，有55%概率使自身获得以下效果：恢复自身兵力（治疗率100%一111.1%，受最高属性影响）：受到伤害降低10%一11.1%，持续1回合，每个效果独立判断",
  },
  {
    season: "S4",
    name: "经天纬地",
    type: "主动",
    probability: 0.45,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "准备1回合，对敌军全体造成130%->144.4%谋略伤害，并有40%->44.4%概率使目标随机获得1种控制状态，持续2回合",
  },
  {
    season: "S1",
    name: "三令五申",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军全体",
    description: "战斗开始前3回合，我军全体造成主动战法伤害提升15%，第4回合起，我军全体受到主动战法伤害降低15%",
  },
  {
    season: "S1",
    name: "文台萌卫",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军前排",
    description: "我军前排受到伤害降低12%(受统率影响)，持续4回合，并且每次受到伤害后有30%概率恢复兵力(治疗率60%，受统率影响)",
  },
  {
    season: "S1",
    name: "斩将拔城",
    type: "主动",
    probability: 0.5,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军单体",
    description: "对敌军统率最低单体造成180%兵刃伤害，若目标处于控制状态，则额外造成180%兵刃伤害",
  },
  {
    season: "S12",
    name: "诱敌深入",
    type: "主动",
    probability: 0.7,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "嘲讽全体敌军,持续1回合,并获得2.5%→2.7%(受先攻影响)当前兵力的伏兵。伏兵:功能性增益状态，数量上限1500,回合结束时消失,受到伤害时，消耗伏兵抵挡其中50%的伤害,并使伤害来源产生等额逃兵",
  },
  {
    season: "S12",
    name: "风助火势",
    type: "主动",
    probability: 0.7,
    traitType: "文武",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体施加风暴和火攻，持续1回合,若目标已持有风暴状态,则额外使其武力降低10→11.1点(受武力影响)持续1回合;若目标已持有火攻状态，则额外使其智力降低10→11.1点(受智力影响),持续1回合",
  },
  {
    season: "S12",
    name: "瞋目横矛",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机单体",
    description: "战斗开始时,使我军随机单体(优先前排)获得横矛:造成伤害后,有25%→27.7%概率(受横矛持有者武力影响)对目标施加畏惧(每回合每名敌军最多触发1次)持续1回合,若目标已持有畏惧,则兵刃伤害提升1%→1.1%(受横矛持有者武力影响),可叠加",
  },
  {
    season: "S13",
    name: "恩威并行",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军单体",
    description: "战斗开始前3回合，自带战法造成治疗后（攻心和倒戈无效），令目标受到伤害降低1.5%->1.67%（受智力和统率影响），可叠加6次，持续到战斗结束；第4回合起，每回合行动时，对敌军随机两人造成25%->27.78%谋略伤害（额外受全队累积治疗量影响）",
  },
  {
    season: "S13",
    name: "未雨绸缪",
    type: "主动",
    probability: 0.6,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机两人",
    description: "获得1层抵御，且奇谋几率和奇谋伤害提升4%->4.44%（受智力影响，自身每存在1种功能性增益状态，额外提升1%->1.11%，最多可提升8次），持续2回合，然后对敌军随机两人造成70%->77.78%谋略伤害",
  },
  {
    season: "S1",
    name: "锋矢阵",
    type: "指挥",
    probability: 1.0,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军全体",
    description: "战斗开始前3回合，我军前排受到伤害降低15%，我军后排造成伤害提升15%",
  },
  {
    season: "S1",
    name: "镇压黄巾",
    type: "主动",
    probability: 0.5,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成80%兵刃伤害，若目标为黄巾军，则额外造成40%兵刃伤害",
  },
  {
    season: "S1",
    name: "闪击",
    type: "主动",
    probability: 0.45,
    traitType: "兵刃",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "对敌军随机单体造成110%兵刃伤害，并使其受到兵刃伤害提升7.5%，持续2回合",
  },
  {
    season: "S1",
    name: "问鼎中原",
    type: "主动",
    probability: 0.5,
    traitType: "谋略",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军全体",
    description: "对敌军全体造成60%谋略伤害，并有35%概率使其随机获得1种控制状态，持续1回合",
  },
  {
    season: "S1",
    name: "陷阵营",
    type: "指挥",
    probability: 1.0,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军全体",
    description: "战斗开始前3回合，我军全体受到伤害降低10%，并获得1层抵御",
  },
  {
    season: "S1",
    name: "雄才大略",
    type: "主动",
    probability: 0.45,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "提升自身15点武力，持续2回合，并使自身下一次主动战法伤害提升20%",
  },
  {
    season: "S1",
    name: "顽抗",
    type: "主动",
    probability: 0.5,
    traitType: "防御",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "敌军随机单体",
    description: "嘲讽敌军随机单体，并使自身受到伤害降低10%，持续2回合",
  },
  {
    season: "S1",
    name: "骁将疾驱",
    type: "主动",
    probability: 0.45,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "提升自身15点武力，持续2回合，并使自身下一次主动战法伤害提升20%",
  },
  {
    season: "S1",
    name: "鲁莽",
    type: "主动",
    probability: 0.5,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "自身",
    description: "使自身获得洞察，持续2回合，并恢复自身兵力(治疗率65%，受武力影响)",
  },
  {
    season: "S1",
    name: "鼓舞",
    type: "主动",
    probability: 0.5,
    traitType: "辅助",
    troopType: "盾兵,弓兵,长枪兵,骑兵",
    target: "我军随机两人",
    description: "提升我军随机两人15点武力，持续2回合",
  },
];
